#!/bin/bash

set -e

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    # Remove vendor logos alternative, all slaves get removed automatically
    update-alternatives --remove \
            vendor-logos \
            /usr/share/desktop-base/kaisen-logos

    # Remove background alternatives for theme packages
    while read theme filename; do
        update-alternatives --remove \
            desktop-background \
            /usr/share/desktop-base/$theme-theme/wallpaper/contents/images/$filename
    done << EOF
kaisen 3840x2160.png
kaisen 2880x1620.png
kaisen 1920x1080.png
block-black-dragon 3840x2160.png
block-black-dragon 2880x1620.png
block-black-dragon 1920x1080.png
block-white-dragon 3840x2160.png
block-white-dragon 2880x1620.png
block-white-dragon 1920x1080.png
dna-center 3840x2160.png
dna-center 2880x1620.png
dna-center 1920x1080.png
dna-left 3840x2160.png
dna-left 2880x1620.png
dna-left 1920x1080.png
line-red 3840x2160.png
line-red 2880x1620.png
line-red 1920x1080.png
line-white 3840x2160.png
line-white 2880x1620.png
line-white 1920x1080.png
picto-red 3840x2160.png
picto-red 2880x1620.png
picto-red 1920x1080.png
picto-white 3840x2160.png
picto-white 2880x1620.png
picto-white 1920x1080.png
tobas 3840x2160.png
tobas 2880x1620.png
tobas 1920x1080.png
EOF
    # *Last* remove background *highest priority* alternatives for active theme
    update-alternatives --remove desktop-background /usr/share/desktop-base/active-theme/wallpaper/contents/images/3840x2160.png

    # Remove desktop-background.xml alternatives
    # For theme packages
    while read theme; do
        update-alternatives --remove \
            desktop-background.xml \
            /usr/share/desktop-base/$theme-theme/wallpaper/gnome-background.xml
    done << EOF
kaisen
block-black-dragon
block-white-dragon
dna-center
dna-left
line-red
line-white
picto-red
picto-white
tobas
EOF
    # *Lastly* remove *highest priority* alternative for active theme
    update-alternatives --remove \
        desktop-background.xml \
        /usr/share/desktop-base/active-theme/wallpaper/gnome-background.xml

    # Remove desktop-lockscreen.xml alternatives
    # For theme packages
    while read theme; do
        update-alternatives --remove \
            desktop-lockscreen.xml \
            /usr/share/desktop-base/$theme-theme/lockscreen/gnome-background.xml
    done << EOF
kaisen
block-black-dragon
block-white-dragon
dna-center
dna-left
line-red
line-white
picto-red
picto-white
tobas
EOF
    # *Last* remove *highest priority* alternative for active theme
    update-alternatives --remove \
        desktop-lockscreen.xml \
        /usr/share/desktop-base/active-theme/lockscreen/gnome-background.xml

    # Remove Plasma 5/KDE wallpaper alternatives
    # For theme packages
    while read theme; do
        update-alternatives --remove \
            desktop-plasma5-wallpaper \
            /usr/share/desktop-base/$theme-theme/wallpaper
    done << EOF
kaisen
block-black-dragon
block-white-dragon
dna-center
dna-left
line-red
line-white
picto-red
picto-white
tobas
EOF
    # *Last* remove *highest priority* alternative for active theme
    update-alternatives --remove \
        desktop-plasma5-wallpaper \
        /usr/share/desktop-base/active-theme/wallpaper

    # Remove login theme alternatives
    # For theme packages
    # Alternative for theme packages
    while read theme background; do
        update-alternatives --remove \
            desktop-login-background \
            /usr/share/desktop-base/$theme-theme/login/$background
    done << EOF
kaisen background.png
block-black-dragon background.png
block-white-dragon background.png
dna-center background.png
dna-left background.png
line-red background.png
line-white background.png
picto-red background.png
picto-white background.png
tobas background.png
EOF
    # *Last* remove *highest priority* alternative for active theme
    update-alternatives --remove \
        desktop-login-background \
        /usr/share/desktop-base/active-theme/login/background.png

    # Remove GRUB background alternatives
    while read theme ratio; do
        update-alternatives --remove \
            desktop-grub \
            /usr/share/desktop-base/$theme-theme/grub/grub-$ratio.png
    done << EOF
kaisen 4x3
kaisen 16x9
block-black-dragon 4x3
block-black-dragon 16x9
block-white-dragon 4x3
block-white-dragon 16x9
dna-center 4x3
dna-center 16x9
dna-left 4x3
dna-left 16x9
line-red 4x3
line-red 16x9
line-white 4x3
line-white 16x9
picto-red 4x3
picto-red 16x9
picto-white 4x3
picto-white 16x9
tobas 4x3
tobas 16x9
EOF
    ## *Lastly* remove *highest priority* alternative
    num_grub_efi_installed=$(dpkg-query --list "grub-efi*" 2> /dev/null | grep "^i" | wc -l)
    if [ $num_grub_efi_installed -gt 0 ] ; then
        remove_first_ratio=4x3
        remove_last_ratio=16x9
    else
        remove_first_ratio=16x9
        remove_last_ratio=4x3
    fi
    update-alternatives --remove \
        desktop-grub.sh \
        /usr/share/desktop-base/active-theme/grub/grub_background.sh
    update-alternatives --remove \
        desktop-grub \
        /usr/share/desktop-base/active-theme/grub/grub-$remove_first_ratio.png
    update-alternatives --remove \
        desktop-grub \
        /usr/share/desktop-base/active-theme/grub/grub-$remove_last_ratio.png


    # Remove theme package alternatives
    while read theme; do
        update-alternatives --remove \
            desktop-theme \
            /usr/share/desktop-base/$theme-theme
    done << EOF
kaisen
block-black-dragon
block-white-dragon
dna-center
dna-left
line-red
line-white
picto-red
picto-white
tobas
EOF
    ## *Lastly* remove *highest priority* alternative
    update-alternatives --remove \
        desktop-theme \
        /usr/share/desktop-base/kaisen-theme

fi